// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Infotecs.Attika.AttikaSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class СохранениеНовойСтатьиНаСерверFeature : Xunit.ICollectionFixture<СохранениеНовойСтатьиНаСерверFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NewArticle.feature"
#line hidden
        
        public СохранениеНовойСтатьиНаСерверFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Сохранение новой статьи на сервер", "Для того, чтобы опубликовать новую статью\r\nКак пользователь\r\nЯ хочу задать заголо" +
                    "вок и текст и нажать сохранить", ProgrammingLanguage.CSharp, new string[] {
                        "NewArticle"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(СохранениеНовойСтатьиНаСерверFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Сохранение новой статьи на сервер")]
        [Xunit.TraitAttribute("Description", "Опубликовать статью сразу после запуска")]
        public virtual void ОпубликоватьСтатьюСразуПослеЗапуска()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Опубликовать статью сразу после запуска", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("я запускаю программу AttikaGui", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 11
 testRunner.And("и вижу заготовку под новую статью", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 12
 testRunner.When("я ввожу Заголовок", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 13
  testRunner.And("ввожу Текст", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 14
  testRunner.And("нажимаю кнопку Сохранить", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 15
 testRunner.Then("должно отобразиться \"ок\" в статусе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 16
  testRunner.And("на панели навигации добавиться новая статья", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                СохранениеНовойСтатьиНаСерверFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                СохранениеНовойСтатьиНаСерверFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
