//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("Attika")]
[assembly: System.Reflection.AssemblyCompany("Infotecs")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2015 Infotecs")]
[assembly: System.Reflection.AssemblyTrademark("SimpleApp")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("Compiled By Ivanov.Kirill")]


